### ISSUE TITLE
RakuDist - module installation fails on Debian/Alpine

### ISSUE THREAD

**Issue by melezhik** [raku-community-modules/App-MoarVM-Debug#11]
RakuDist reports installation fails:

http://repo.westus.cloudapp.azure.com/rakudist/reports/App%3A%3AMoarVM%3A%3ADebug/debian/1579218335.txt

http://repo.westus.cloudapp.azure.com/rakudist/reports/App%3A%3AMoarVM%3A%3ADebug/debian/1579218445.txt

**Comment by jnthn** [comment]
Looks like a dependency issue:

> 23:46:32 01/16/2020 [bash: Install App::MoarVM::Debug dependencies] ===> Fetching [FAIL]: Data::MessagePack:ver<0.1.2> from git@github.com:pierre-vigier/Perl6-Data-MessagePack.git

**Comment by melezhik** [comment]
yes

**Comment by melezhik** [comment]
Data::MessagePack itself is not installable, don't know why, though listed in modules.perl6.org

http://repo.westus.cloudapp.azure.com/rakudist/reports/Data%3A%3AMessagePack/debian/1579229866.txt

**Comment by Altai-man** [comment]
It is an issue in Data::MessagePack, its url is broken for some time since the new ecosystem does not mangle urls from META6.json. I am sure there are a couple of PRs sent to address this already, but still.

**Comment by lizmat** [comment]
This appears fixed
