### ISSUE TITLE
moarvm-remote locks when stepping too fast

### ISSUE THREAD

**Issue by eiselekd** [raku-community-modules/App-MoarVM-Debug#14]
When stepping and continue pressing return the debug protocol seems to
get out of sync and ```moar-remote``` will stop responding, requiring to 
restart moar-remote.

It start 
```nqp-m --debug-port=9999 --debug-suspend -e "my $a := 1;"```
and 
```moar-remote 9999```

then I enable debug and do a "step into 1". Then I keep the "Return" pressed.
See 
[x.txt](https://github.com/edumentab/p6-app-moarvm-debug/files/4642395/x.txt)
At the end moar-remote seems to hang and  I need to close moar-remote and restart it.

Can you give a tip where to look if I want to fix this?  The asynchronous threading networking
code is quite hard to understand.

**Comment by lizmat** [comment]
Is this still an issue?

**Comment by eiselekd** [comment]
I guess you can close it

**Comment by timo** [comment]
https://github.com/raku-community-modules/App-MoarVM-Debug/commit/7f992bbb19c7dcc9d880e3f0d649d70c8adc9951 this should also fix the problem
